# Generated by Django 5.1 on 2024-08-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='course_images/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('trainer_img', models.ImageField(upload_to='trainer_images/')),
                ('trainer_name', models.CharField(max_length=200)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_available', models.IntegerField()),
                ('schedule_time', models.DateTimeField()),
                ('course_video', models.FileField(upload_to='course_videos/')),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
    ]
