# Generated by Django 5.1 on 2024-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
