# Generated by Django 5.1 on 2024-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_app', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
