# Generated by Django 5.1 on 2024-09-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_app', '0003_course_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='likes_count',
        ),
    ]
